detector:
  type: DetectionModel
  num_classes: 3
  preprocessor_cfg:
    type: TensorPreprocessor
  postprocessor_cfg:
    type: YOLOObjectnessPostprocessor
    conf_thresh: 0.01
    nms_thresh: 0.5
    class_agnostic: true
    num_classes: 1
  model_cfg:
    in_channels: 1
    backbone:
      - [-1, 1, Conv, [64, 7, 2, 3]]
      - [-1, 1, nn.MaxPool2d, [3, 2, 1]]
      - [-1, 1, C2f, [64, false]]
      - [-1, 1, Conv, [128, 3, 2]]
      - [-1, 1, C2f, [128, false]]
      - [-1, 1, Conv, [256, 3, 2]]
      - [-1, 1, C2f, [256, false]]
    head:
      - [-1, 1, SPPF, [512, 5]]
      - [-1, 1, Detect, [512, true]]
      - [-1, 1, DetectDecode, [[{"name": "p3", "stride": 16}]]]
      - [-1, 1, DetectContract, []]

loss:
  type: YoloRTCriterion
  num_classes: 3
  loss_obj_weight: 1.0
  loss_box_weight: 5.0
  loss_obj_empty_factor: 0.25
