detector:
  type: YOLORTv1
  num_classes: 3
  stride: 16
  conf_thresh: 0.01
  nms_thresh: 0.5
  preprocessor_cfg:
    type: TensorPreprocessor
  postprocessor_cfg:
    type: YOLOObjectnessPostprocessor
    conf_thresh: 0.01
    nms_thresh: 0.5
    class_agnostic: true
    num_classes: 1
  trainable: false
  deploy: false
  backbone_cfg:
    type: ResNet18
    in_channels: 1
    pretrained: false
    pretrained_path: null
  neck_cfg:
    type: SPPF
    in_dim: 256
    out_dim: 512
    expand_ratio: 0.5
    pooling_size: 5
    act_type: lrelu
    norm_type: BN
  head_cfg:
    type: DecoupledHead
    num_cls_head: 2
    num_reg_head: 2
    act_type: lrelu
    norm_type: BN
    depthwise: false

loss:
  type: YoloRTCriterion
  num_classes: 3
  loss_obj_weight: 1.0
  loss_box_weight: 5.0
  loss_obj_empty_factor: 0.25
