strategy:
  optimizer:
    optimizer: adamw          # adamw | adam | sgd
    lr0: 0.0003
    momentum: 0.937
    weight_decay: 0.0005
  scheduler:
    scheduler: cosine         # cosine | linear
    lrf: 0.01                 # 最终 lr = lr0 * lrf
    warmup_bias_lr: 0.1
    warmup_momentum: 0.8
  train:
    max_epoch: 50
    fp16: false
    warmup_epoch: 3
    eval_interval: 5
    clip_grad: 10.0
    num_workers_train: 4
    num_workers_test: 0
    persistent_workers: false
  eval:
    iou_thresh: 0.5
    save_folder: outputs/weights
    resume: null
  vis_pred_full: false

deterministic: false
