strategy:
  optimizer:
    type: AdamW
    lr: 0.0003
    weight_decay: 0.01
  scheduler:
    type: CosineAnnealingLR
    warmup_epochs: 1
  trainer:
    type: EpochBasedTrainer
    amp: true
    grad_clip_norm: 5.0
