dataset:
  type: RadarWindowDataset
  mat_dir: G:\Data\data
  csv_path: G:\Data\data\data_mat.csv
  window_size: [640, 640]
  stride: [640, 640]
  complex_mode: abs
  subset: train
  azimuth_split_ratio: 0.7
  cache_mat_files: 4
  filter_difficult: false

dataloader:
  batch_size: 4
  num_workers: 4
  shuffle: false

train_transforms:
  - type: SeaClutterInjection
    prob: 0.7
    snr_db_range: [5.0, 20.0]
    background_only: false
  - type: RandomVerticalFlip
    prob: 0.5
  - type: AmplitudeNormalize
    mode: db_percentile
  - type: PadToStride
    stride: 32